# Generated by Django 5.1.1 on 2024-09-14 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personajes',
            name='arma',
            field=models.CharField(choices=[('Mandoble', 'MANDOBLE'), ('Espada Ligera', 'ESPADA_LIGERA'), ('Arco', 'ARCO'), ('Catalizador', 'CATALIZADOR'), ('Lanza', 'LANZA')], max_length=15),
        ),
        migrations.AlterField(
            model_name='personajes',
            name='vision',
            field=models.CharField(choices=[('Pyro', 'PYRO'), ('Hydro', 'HYDRO'), ('Dendro', 'DENDRO'), ('Electro', 'ELECTRO'), ('Cyro', 'CYRO'), ('Geo', 'GEO'), ('Anemo', 'ANEMO')], max_length=10),
        ),
    ]
